export const LOGIN_ACTION = "LOGIN";
export const LOGOUT_ACTION = "LOGOUT";
export const SIGNUP_ACTION = "SIGNUP";
export const LOGIN_SUCCESS = "LOGIN_SUCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_ERROR = "LOGOUT_ERROR";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const PROGRESS = "PROGRESS";
export const SWITCHLANGUAGE = "SWITCHALNGUAGE";


export const ACTION_REPOSITORIES_LIST = "ACTION_REPOSITORIES_LIST";
export const ACTION_LIST_ERROR = "ACTION_LIST_ERROR";
export const ACTION_LIST_SUCCESS = "ACTION_LIST_SUCCESS";


export const ACTION_README = "ACTION_README";
export const ACTION_README_SUCCESS = "ACTION_README_SUCCESS";
export const ACTION_README_ERROR = "ACTION_README_ERROR";

export const PROFILE_GETUSERINFO = "PROFILE_GETUSERINFO";
export const PROFILE_GETUSERINFO_SUCCESS = "PROFILE_GETUSERINFO_SUCCESS";
export const PROFILE_GETUSERINFO_ERROR = "PROFILE_GETUSERINFO_ERROR";