import LocalizedStrings from "react-localization";

module.exports = new LocalizedStrings({
    en: {
        signin: 'Sign In',
        signup: 'Sign Up',
        password: 'Password',
        email: 'Email',
        login: 'Login',
        dont_have_an_account: 'Don\'t have an account?',
        firstName: 'First Name',
        lastName: 'Last Name',
        already_have_an_account: 'Already have an account?',
        categories: 'Categories',
        brands: 'Brands',
        machines: 'Machines',
        tape: 'Tape',
        sale: 'SALE',
        upto: 'UPTO',
        off: 'OFF',
        aboutus: 'About Us',
        products: 'Products',
        portfolio: 'Portfolio',
        findus: 'Find Us',
        services: 'Services',
        bookingOnline: 'Booking Online',
        signout: 'Sign Out',
        description: 'Description',
        reviews: 'Reviews',
        shipping_returns: 'Shipping & Returns',
        addToCart: 'Add To Cart',
        buyNow: 'Buy Now',
        sendreview: 'Send Review',
        shipping_returns: 'Shipping & Returns',
        returns_policy: 'Returns Policy',
        shipping: 'Shipping',
        ourwork: 'Our Work',
        packaging_equipment: 'Packaging Equipment',
        metal_plating: 'Metal Plating',
        mobileCanning: 'Mobile Canning',
        comingsoon: 'Coming Soon',
        shopParts: 'Shop Parts',
        shopServices: 'Shop Services',
        name: 'Name',
        message: 'Message',
        send: 'Send',
        sort: 'Sort',
        filter: 'Filter',
        showDetail: 'Show Details',
        continue: 'Continue'
    }
});
