export default {
    EMAIL_REGEX: /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
    MIN_PASSWORD_LENGTH: 6,
    CLIENT_ID: 'ffb12e79140e7b6597ba',
    CLIENT_SECRET: 'd07dadbce095325cebfc40a46eb467e906063927',
    BASE_HEADER: {
        'Accept': 'application/vnd.github.v3.full+json',
        'Content-Type': 'application/json',
    },
    BASE_PAGE_LIMIT: 10,
    LOGIN_SCREEN: 'Login',
    SIGNUP_SCREEN: 'Signup',
    DASHBOARD_SCREEN: 'Dashboard',
    INNERPRODUCT_SCREEN: 'InnerProduct',
    DESCRIPTION_SCREEN: 'Description',
    REVIEW_SCREEN: 'Review',
    SHIPPING_RETURENS_SCREEN: 'Shipping_Returns',
    SERVICES_SCREEN: 'Services',
    PORTFOLIO_SCREEN: 'Portfolio',
    ABOUTUS_SCREEN: 'AboutUs',
    FINDUS_SCREEN: 'FindUs',
    PRODUCTS_SCREEN: 'Products',
    CART_SCREEN: 'Cart',
    CHAT_SCREEN: 'Chat',
    HARDWARE_PRESS_EVENT: 'hardwareBackPress',
}